### ISSUE TITLE
Some issues about evaluation metrics（semSQL or SQL?）

### ISSUE THREAD

**Issue by tom68-ll** [Bahuia/C3#1]
Dear Author,
We come from the SFNET. Congratulations on your new paper being accepted. We still have some questions regarding the evaluation metrics. We noticed that in SFNET, you have used IRNET's intermediate representation as a benchmark for evaluation, rather than the final SQL. 
In this context, could you clarify whether the results reported in your paper are based on the accuracy of the intermediate representation or the final SQL accuracy (since we noticed that you have made comparisons with methods based on GRAPPA and T5 as well)? This information is crucial for us to gain further insights.

**Comment by ZSY-SZ** [comment]
Hi, thanks for your attention on our work. In this paper, we use [the official evaluation scripts](https://github.com/taoyds/spider/blob/master/evaluation.py) provided by the Spider dataset to evaluate the accuracy and you can find our modified codes [here](https://github.com/Bahuia/C3/blob/main/train/train_utils/spider/evaluation.py).

**Comment by tom68-ll** [comment]
Thanks for your answer!
